ALTER TABLE events ADD COLUMN result VARCHAR(1) DEFAULT NULL;
ALTER TABLE bet_items MODIFY money DECIMAL(8,2) DEFAULT NULL;
ALTER TABLE bet_items MODIFY ev FLOAT(10,2) DEFAULT NULL;
ALTER TABLE bet_items ADD COLUMN income FLOAT(15,2) DEFAULT NULL;
ALTER TABLE bets MODIFY ev FLOAT(10,2) DEFAULT NULL;
ALTER TABLE bets MODIFY income FLOAT(15,2) DEFAULT NULL;
ALTER TABLE bets MODIFY last_bet_ev FLOAT(10,2) DEFAULT NULL;
